<?php

declare(strict_types=1);

namespace EnterpriseCPT\Templates;

/**
 * Resolves the PHP template for a given block slug using a three-tier lookup:
 *
 * 1. Active theme:       {theme}/enterprise-cpt/blocks/{slug}.php
 * 2. Persistent storage: wp-content/uploads/enterprise-cpt/templates/{slug}.php
 * 3. Plugin fallback:    plugin/templates/generic-block.php
 */
final class Resolver
{
    private const GENERATED_TEMPLATE_MARKER = 'Auto-generated by Enterprise CPT.';

    /**
     * Return the absolute path to the template file for the given block slug.
     * Always returns a valid path (never null) because the plugin fallback always exists.
     */
    public static function get_block_template(string $slug): string
    {
        $slug = sanitize_key($slug);

        // 1. Active theme (child theme first via get_stylesheet_directory, then parent via get_template_directory).
        $themeTemplate = get_stylesheet_directory() . "/enterprise-cpt/blocks/{$slug}.php";

        if (is_readable($themeTemplate)) {
            return $themeTemplate;
        }

        $parentTemplate = get_template_directory() . "/enterprise-cpt/blocks/{$slug}.php";

        if ($parentTemplate !== $themeTemplate && is_readable($parentTemplate)) {
            return $parentTemplate;
        }

        // Legacy path support (enterprise-cpts with trailing 's').
        $legacyTheme = get_stylesheet_directory() . "/enterprise-cpts/blocks/{$slug}.php";

        if (is_readable($legacyTheme)) {
            return $legacyTheme;
        }

        // 2. Persistent storage (uploads directory).
        $uploadsDir = wp_upload_dir(null, false);
        $uploadsTemplate = $uploadsDir['basedir'] . "/enterprise-cpt/templates/{$slug}.php";

        if (is_readable($uploadsTemplate)) {
            return $uploadsTemplate;
        }

        // 3. Plugin fallback.
        return ENTERPRISE_CPT_PATH . 'templates/generic-block.php';
    }

    /**
     * Render a block template with the given group and attributes.
     *
     * @param array $group      The field group definition array.
     * @param array $attributes The block attributes array.
     * @return string Rendered HTML.
     */
    public static function render_block(array $group, array $attributes): string
    {
        $slug = sanitize_key((string) ($group['name'] ?? ''));

        if ($slug === '') {
            return '';
        }

        $templatePath = self::get_block_template($slug);

        // Build $fields as an array so templates always get a consistent type.
        $fields = self::build_fields_array($group, $attributes);

        if (self::isGeneratedUploadsTemplate($templatePath)) {
            return self::render_default_block_markup($group, $fields);
        }

        // Also expose $group for templates that need field metadata.
        ob_start();
        include $templatePath;
        return (string) ob_get_clean();
    }

    /**
     * Render the default schema-aware markup for a block.
     *
     * @param array<string, mixed> $group
     * @param array<string, mixed> $fields
     */
    public static function render_default_block_markup(array $group, array $fields): string
    {
        $title = esc_html((string) ($group['title'] ?? $group['name'] ?? 'Field Group'));
        $slug = esc_attr(sanitize_key((string) ($group['name'] ?? '')));
        $fieldDefinitions = is_array($group['fields'] ?? null) ? $group['fields'] : [];
        $items = [];

        foreach ($fieldDefinitions as $fieldDefinition) {
            if (! is_array($fieldDefinition)) {
                continue;
            }

            $name = (string) ($fieldDefinition['name'] ?? '');

            if ($name === '') {
                continue;
            }

            $itemMarkup = self::render_block_field_markup(
                $fieldDefinition,
                $fields[$name] ?? ($fieldDefinition['default'] ?? '')
            );

            if ($itemMarkup !== '') {
                $items[] = $itemMarkup;
            }
        }

        if ($items === []) {
            return '';
        }

        return sprintf(
            '<div class="enterprise-cpt-block enterprise-cpt-block--%1$s"><h2 class="enterprise-cpt-block__title">%2$s</h2><div class="enterprise-cpt-block__fields">%3$s</div></div>',
            $slug,
            $title,
            implode('', $items)
        );
    }

    /**
     * Render one block field using the shared frontend schema rules.
     *
     * @param array<string, mixed> $fieldDefinition
     */
    public static function render_block_field_markup(array $fieldDefinition, mixed $value): string
    {
        $name = (string) ($fieldDefinition['name'] ?? '');

        if ($name === '' || str_starts_with($name, '_')) {
            return '';
        }

        $type = sanitize_key((string) ($fieldDefinition['type'] ?? 'text'));
        $label = (string) ($fieldDefinition['label'] ?? $name);
        $valueMarkup = self::render_block_field_value_markup($fieldDefinition, $value);

        if ($valueMarkup === '') {
            return '';
        }

        return sprintf(
            '<div class="enterprise-cpt-block__field enterprise-cpt-block__field--%1$s"><span class="enterprise-cpt-block__label">%2$s:</span>%3$s</div>',
            esc_attr($type),
            esc_html($label),
            $valueMarkup
        );
    }

    /**
     * @param array<string, mixed> $fieldDefinition
     */
    private static function render_block_field_value_markup(array $fieldDefinition, mixed $value): string
    {
        $type = sanitize_key((string) ($fieldDefinition['type'] ?? 'text'));

        return match ($type) {
            'image' => self::render_top_level_image_markup($value, $fieldDefinition),
            'true_false' => sprintf(
                '<span class="enterprise-cpt-block__value">%s</span>',
                esc_html(! empty($value) ? 'Yes' : 'No')
            ),
            'textarea' => ($value === null || $value === '')
                ? ''
                : '<div class="enterprise-cpt-block__value">' . wp_kses_post(wpautop((string) $value)) . '</div>',
            'repeater' => self::render_repeater_markup($fieldDefinition, $value),
            default => self::render_scalar_markup($value),
        };
    }

    private static function render_scalar_markup(mixed $value, string $class = 'enterprise-cpt-block__value'): string
    {
        if ($value === null || $value === '') {
            return '';
        }

        if (is_array($value)) {
            if ($value === []) {
                return '';
            }

            $value = wp_json_encode($value);
        }

        return sprintf('<span class="%1$s">%2$s</span>', esc_attr($class), esc_html((string) $value));
    }

    /**
     * @param array<string, mixed> $fieldDefinition
     */
    private static function render_top_level_image_markup(mixed $value, array $fieldDefinition): string
    {
        $image = self::render_image_markup($value, $fieldDefinition, 'enterprise-cpt-block__image');

        if ($image === '') {
            return '';
        }

        return '<span class="enterprise-cpt-block__value">' . $image . '</span>';
    }

    /**
     * @param array<string, mixed> $fieldDefinition
     */
    private static function render_repeater_markup(array $fieldDefinition, mixed $value): string
    {
        $rows = self::normalize_repeater_rows($value);

        if ($rows === []) {
            return '';
        }

        $subfieldSchemas = [];

        foreach (is_array($fieldDefinition['rows'] ?? null) ? $fieldDefinition['rows'] : [] as $subfield) {
            if (! is_array($subfield)) {
                continue;
            }

            $subfieldName = (string) ($subfield['name'] ?? '');

            if ($subfieldName !== '') {
                $subfieldSchemas[$subfieldName] = $subfield;
            }
        }

        $rowMarkup = [];

        foreach ($rows as $row) {
            if (! is_array($row) || $row === []) {
                continue;
            }

            $columnMarkup = [];

            foreach ($row as $columnName => $columnValue) {
                $columnSchema = is_array($subfieldSchemas[(string) $columnName] ?? null)
                    ? $subfieldSchemas[(string) $columnName]
                    : [];
                $columnType = sanitize_key((string) ($columnSchema['type'] ?? 'text'));
                $columnLabel = (string) ($columnSchema['label'] ?? ucwords(str_replace('_', ' ', (string) $columnName)));
                $columnValueMarkup = match ($columnType) {
                    'image' => self::render_image_markup($columnValue, $columnSchema, 'enterprise-cpt-block__repeater-image'),
                    'true_false' => self::render_scalar_markup(! empty($columnValue) ? 'Yes' : 'No', 'enterprise-cpt-block__repeater-value'),
                    'textarea' => ($columnValue === null || $columnValue === '')
                        ? ''
                        : '<div class="enterprise-cpt-block__repeater-value">' . wp_kses_post(wpautop((string) $columnValue)) . '</div>',
                    default => self::render_scalar_markup($columnValue, 'enterprise-cpt-block__repeater-value'),
                };

                if ($columnValueMarkup === '') {
                    continue;
                }

                $columnMarkup[] = sprintf(
                    '<li class="enterprise-cpt-block__repeater-column enterprise-cpt-block__repeater-column--%1$s"><span class="enterprise-cpt-block__repeater-label">%2$s:</span>%3$s</li>',
                    esc_attr($columnType),
                    esc_html($columnLabel),
                    $columnValueMarkup
                );
            }

            if ($columnMarkup !== []) {
                $rowMarkup[] = '<ul class="enterprise-cpt-block__repeater-row">' . implode('', $columnMarkup) . '</ul>';
            }
        }

        if ($rowMarkup === []) {
            return '';
        }

        return '<div class="enterprise-cpt-block__value enterprise-cpt-block__value--repeater">' . implode('', $rowMarkup) . '</div>';
    }

    private static function normalize_repeater_rows(mixed $value): array
    {
        if (is_array($value)) {
            return $value;
        }

        if (! is_string($value) || $value === '') {
            return [];
        }

        $decoded = json_decode($value, true);

        return is_array($decoded) ? $decoded : [];
    }

    /**
     * @param array<string, mixed> $fieldDefinition
     */
    private static function render_image_markup(mixed $attachmentId, array $fieldDefinition, string $class): string
    {
        $id = (int) $attachmentId;

        if ($id <= 0) {
            return '';
        }

        $size = sanitize_key((string) ($fieldDefinition['image_size'] ?? 'medium'));
        $link = sanitize_key((string) ($fieldDefinition['image_link'] ?? 'none'));
        $image = wp_get_attachment_image($id, $size !== '' ? $size : 'medium', false, [
            'class' => $class,
            'loading' => 'lazy',
        ]);

        if (! is_string($image) || $image === '') {
            return '';
        }

        if ($link === 'file') {
            $url = wp_get_attachment_url($id);

            if ($url) {
                return sprintf('<a href="%s">%s</a>', esc_url($url), $image);
            }
        }

        if ($link === 'attachment') {
            $url = get_attachment_link($id);

            if ($url) {
                return sprintf('<a href="%s">%s</a>', esc_url($url), $image);
            }
        }

        return $image;
    }

    private static function isGeneratedUploadsTemplate(string $templatePath): bool
    {
        $uploadsDir = wp_upload_dir(null, false);
        $uploadsTemplateDir = trailingslashit($uploadsDir['basedir'] . '/enterprise-cpt/templates');

        if (! str_starts_with($templatePath, $uploadsTemplateDir) || ! is_readable($templatePath)) {
            return false;
        }

        $contents = @file_get_contents($templatePath, false, null, 0, 512);

        return is_string($contents) && str_contains($contents, self::GENERATED_TEMPLATE_MARKER);
    }

    /**
     * Build an associative array of field values from block attributes.
     *
     * @return array<string, mixed>
     */
    public static function build_fields_array(array $group, array $attributes): array
    {
        $fields = [];

        foreach (($group['fields'] ?? []) as $field) {
            if (! is_array($field)) {
                continue;
            }

            $name = (string) ($field['name'] ?? '');

            if ($name === '') {
                continue;
            }

            $fields[$name] = $attributes[$name] ?? ($field['default'] ?? '');
        }

        $fields['_block_instance_id'] = $attributes['blockInstanceId'] ?? '';
        $fields['_field_group_slug']  = $attributes['fieldGroupSlug'] ?? '';

        return $fields;
    }

    /**
     * Check whether a theme template exists for the given slug
     * (excludes uploads and plugin fallback).
     */
    public static function has_theme_template(string $slug): bool
    {
        $slug = sanitize_key($slug);

        $paths = [
            get_stylesheet_directory() . "/enterprise-cpt/blocks/{$slug}.php",
            get_template_directory() . "/enterprise-cpt/blocks/{$slug}.php",
            get_stylesheet_directory() . "/enterprise-cpts/blocks/{$slug}.php",
        ];

        foreach ($paths as $path) {
            if (is_readable($path)) {
                return true;
            }
        }

        return false;
    }

    /**
     * Check whether a scaffolded template exists in uploads for the given slug.
     */
    public static function has_uploads_template(string $slug): bool
    {
        $slug = sanitize_key($slug);
        $uploadsDir = wp_upload_dir(null, false);

        return is_readable($uploadsDir['basedir'] . "/enterprise-cpt/templates/{$slug}.php");
    }
}
