<?php

declare(strict_types=1);

namespace EnterpriseCPT\Templates;

/**
 * Scaffolds starter block templates into the uploads directory when
 * a Field Group is saved with is_block => true and no theme template exists.
 */
final class Scaffolder
{
    /**
     * Attempt to scaffold a block template for the given field group.
     *
     * @param string $slug       The sanitized field group slug.
     * @param array  $definition The full field group definition.
     * @return array{scaffolded: bool, path: string, warning: string}
     */
    public function scaffold(string $slug, array $definition): array
    {
        $slug = sanitize_key($slug);

        // If a developer has a theme template, never overwrite — they own it.
        if (Resolver::has_theme_template($slug)) {
            return [
                'scaffolded' => false,
                'path'       => '',
                'warning'    => '',
            ];
        }

        // If a scaffolded template already exists in uploads, skip.
        if (Resolver::has_uploads_template($slug)) {
            return [
                'scaffolded' => false,
                'path'       => '',
                'warning'    => '',
            ];
        }

        // Ensure the uploads directory exists and is secured.
        $uploadsDir = wp_upload_dir(null, false);
        $templateDir = $uploadsDir['basedir'] . '/enterprise-cpt/templates';

        if (! $this->ensureDirectory($templateDir)) {
            return [
                'scaffolded' => false,
                'path'       => '',
                'warning'    => 'Template generation skipped — unable to create directory: ' . $templateDir,
            ];
        }

        $this->writeSecurityFiles($templateDir);

        // Generate and write the template.
        $templateContent = $this->generateTemplate($slug, $definition);
        $targetPath      = $templateDir . "/{$slug}.php";

        $written = @file_put_contents($targetPath, $templateContent); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents

        if ($written === false) {
            return [
                'scaffolded' => false,
                'path'       => $targetPath,
                'warning'    => 'Template generation skipped — unable to write file: ' . $targetPath,
            ];
        }

        return [
            'scaffolded' => true,
            'path'       => $targetPath,
            'warning'    => '',
        ];
    }

    /**
     * Generate a starter PHP template for the given field group.
     */
    private function generateTemplate(string $slug, array $definition): string
    {
        $title  = (string) ($definition['title'] ?? ucwords(str_replace(['-', '_'], ' ', $slug)));
        $fields = is_array($definition['fields'] ?? null) ? $definition['fields'] : [];

        $lines = [];
        $lines[] = '<?php';
        $lines[] = '/**';
        $lines[] = ' * Block template: ' . $title;
        $lines[] = ' *';
        $lines[] = ' * Auto-generated by Enterprise CPT.';
        $lines[] = ' * You may move this file to your theme at:';
        $lines[] = ' *   enterprise-cpt/blocks/' . $slug . '.php';
        $lines[] = ' *';
        $lines[] = ' * Available variables:';
        $lines[] = ' *   $fields — associative array of field values.';
        $lines[] = ' *   $group  — the full field group definition array.';
        $lines[] = ' *';
        $lines[] = ' * @package EnterpriseCPT';
        $lines[] = ' */';
        $lines[] = '';
        $lines[] = 'if ( ! defined( \'ABSPATH\' ) ) {';
        $lines[] = '    exit;';
        $lines[] = '}';
        $lines[] = '';
        $lines[] = '$fields = (array) $fields;';
        $lines[] = '?>';
        $lines[] = '<div class="enterprise-cpt-block enterprise-cpt-block--' . esc_attr($slug) . '">';
        $lines[] = '    <h2>' . esc_html($title) . '</h2>';
        $lines[] = '';

        foreach ($fields as $field) {
            if (! is_array($field)) {
                continue;
            }

            $name  = (string) ($field['name'] ?? '');
            $label = (string) ($field['label'] ?? $name);
            $type  = (string) ($field['type'] ?? 'text');

            if ($name === '' || str_starts_with($name, '_')) {
                continue;
            }

            $varName = '$' . preg_replace('/[^a-z0-9_]/', '_', $name);

            $lines[] = '    <?php ' . $varName . ' = $fields[\'' . addslashes($name) . '\'] ?? \'\'; ?>';

            switch ($type) {
                case 'image':
                    $lines[] = '    <?php if ( (int) ' . $varName . ' > 0 ) : ?>';
                    $lines[] = '        <div class="enterprise-cpt-block__field">';
                    $lines[] = '            <strong>' . esc_html($label) . ':</strong>';
                    $lines[] = '            <?php echo wp_get_attachment_image( (int) ' . $varName . ', \'medium\' ); ?>';
                    $lines[] = '        </div>';
                    $lines[] = '    <?php endif; ?>';
                    break;

                case 'true_false':
                    $lines[] = '    <div class="enterprise-cpt-block__field">';
                    $lines[] = '        <strong>' . esc_html($label) . ':</strong>';
                    $lines[] = '        <?php echo ! empty( ' . $varName . ' ) ? \'Yes\' : \'No\'; ?>';
                    $lines[] = '    </div>';
                    break;

                case 'textarea':
                    $lines[] = '    <?php if ( ' . $varName . ' !== \'\' ) : ?>';
                    $lines[] = '        <div class="enterprise-cpt-block__field">';
                    $lines[] = '            <strong>' . esc_html($label) . ':</strong>';
                    $lines[] = '            <?php echo wp_kses_post( wpautop( (string) ' . $varName . ' ) ); ?>';
                    $lines[] = '        </div>';
                    $lines[] = '    <?php endif; ?>';
                    break;

                default:
                    $lines[] = '    <?php if ( ' . $varName . ' !== \'\' ) : ?>';
                    $lines[] = '        <div class="enterprise-cpt-block__field">';
                    $lines[] = '            <strong>' . esc_html($label) . ':</strong>';
                    $lines[] = '            <span><?php echo esc_html( (string) ' . $varName . ' ); ?></span>';
                    $lines[] = '        </div>';
                    $lines[] = '    <?php endif; ?>';
                    break;
            }

            $lines[] = '';
        }

        $lines[] = '</div>';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * Ensure the target directory exists.
     */
    private function ensureDirectory(string $path): bool
    {
        if (is_dir($path)) {
            return true;
        }

        return wp_mkdir_p($path);
    }

    /**
     * Write security files to prevent direct PHP execution in the uploads template directory.
     */
    private function writeSecurityFiles(string $dir): void
    {
        // index.php to prevent directory listing.
        $indexFile = $dir . '/index.php';

        if (! is_file($indexFile)) {
            @file_put_contents($indexFile, "<?php\n// Silence is golden.\n"); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
        }

        // .htaccess to deny direct execution (Apache).
        $htaccessFile = $dir . '/.htaccess';

        if (! is_file($htaccessFile)) {
            $htaccess = "# Prevent direct PHP execution — templates are included by the plugin.\n";
            $htaccess .= "<Files *.php>\n";
            $htaccess .= "    <IfModule mod_authz_core.c>\n";
            $htaccess .= "        Require all denied\n";
            $htaccess .= "    </IfModule>\n";
            $htaccess .= "    <IfModule !mod_authz_core.c>\n";
            $htaccess .= "        Order deny,allow\n";
            $htaccess .= "        Deny from all\n";
            $htaccess .= "    </IfModule>\n";
            $htaccess .= "</Files>\n";

            @file_put_contents($htaccessFile, $htaccess); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
        }
    }
}
