<?php

declare(strict_types=1);

namespace EnterpriseCPT\Templates;

/**
 * Scaffolds starter block templates into the uploads directory when
 * a Field Group is saved with is_block => true and no theme template exists.
 */
final class Scaffolder
{
    /**
     * Attempt to scaffold a block template for the given field group.
     *
     * @param string $slug       The sanitized field group slug.
     * @param array  $definition The full field group definition.
     * @return array{scaffolded: bool, path: string, warning: string}
     */
    public function scaffold(string $slug, array $definition): array
    {
        $slug = sanitize_key($slug);

        // If a developer has a theme template, never overwrite — they own it.
        if (Resolver::has_theme_template($slug)) {
            return [
                'scaffolded' => false,
                'path'       => '',
                'warning'    => '',
            ];
        }

        // If a scaffolded template already exists in uploads, skip.
        if (Resolver::has_uploads_template($slug)) {
            return [
                'scaffolded' => false,
                'path'       => '',
                'warning'    => '',
            ];
        }

        // Ensure the uploads directory exists and is secured.
        $uploadsDir = wp_upload_dir(null, false);
        $templateDir = $uploadsDir['basedir'] . '/enterprise-cpt/templates';

        if (! $this->ensureDirectory($templateDir)) {
            return [
                'scaffolded' => false,
                'path'       => '',
                'warning'    => 'Template generation skipped — unable to create directory: ' . $templateDir,
            ];
        }

        $this->writeSecurityFiles($templateDir);

        // Generate and write the template.
        $templateContent = $this->generateTemplate($slug, $definition);
        $targetPath      = $templateDir . "/{$slug}.php";

        $written = @file_put_contents($targetPath, $templateContent); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents

        if ($written === false) {
            return [
                'scaffolded' => false,
                'path'       => $targetPath,
                'warning'    => 'Template generation skipped — unable to write file: ' . $targetPath,
            ];
        }

        return [
            'scaffolded' => true,
            'path'       => $targetPath,
            'warning'    => '',
        ];
    }

    /**
     * Generate a starter PHP template for the given field group.
     */
    private function generateTemplate(string $slug, array $definition): string
    {
        $title  = (string) ($definition['title'] ?? ucwords(str_replace(['-', '_'], ' ', $slug)));

        $lines = [];
        $lines[] = '<?php';
        $lines[] = '/**';
        $lines[] = ' * Block template: ' . $title;
        $lines[] = ' *';
        $lines[] = ' * Auto-generated by Enterprise CPT.';
        $lines[] = ' * You may move this file to your theme at:';
        $lines[] = ' *   enterprise-cpt/blocks/' . $slug . '.php';
        $lines[] = ' *';
        $lines[] = ' * Available variables:';
        $lines[] = ' *   $fields — associative array of field values.';
        $lines[] = ' *   $group  — the full field group definition array.';
        $lines[] = ' *';
        $lines[] = ' * @package EnterpriseCPT';
        $lines[] = ' */';
        $lines[] = '';
        $lines[] = 'if ( ! defined( \'ABSPATH\' ) ) {';
        $lines[] = '    exit;';
        $lines[] = '}';
        $lines[] = '';
        $lines[] = '$fields = (array) $fields;';
        $lines[] = 'echo \\EnterpriseCPT\\Templates\\Resolver::render_default_block_markup( (array) $group, $fields );';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * Ensure the target directory exists.
     */
    private function ensureDirectory(string $path): bool
    {
        if (is_dir($path)) {
            return true;
        }

        return wp_mkdir_p($path);
    }

    /**
     * Write security files to prevent direct PHP execution in the uploads template directory.
     */
    private function writeSecurityFiles(string $dir): void
    {
        // index.php to prevent directory listing.
        $indexFile = $dir . '/index.php';

        if (! is_file($indexFile)) {
            @file_put_contents($indexFile, "<?php\n// Silence is golden.\n"); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
        }

        // .htaccess to deny direct execution (Apache).
        $htaccessFile = $dir . '/.htaccess';

        if (! is_file($htaccessFile)) {
            $htaccess = "# Prevent direct PHP execution — templates are included by the plugin.\n";
            $htaccess .= "<Files *.php>\n";
            $htaccess .= "    <IfModule mod_authz_core.c>\n";
            $htaccess .= "        Require all denied\n";
            $htaccess .= "    </IfModule>\n";
            $htaccess .= "    <IfModule !mod_authz_core.c>\n";
            $htaccess .= "        Order deny,allow\n";
            $htaccess .= "        Deny from all\n";
            $htaccess .= "    </IfModule>\n";
            $htaccess .= "</Files>\n";

            @file_put_contents($htaccessFile, $htaccess); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
        }
    }
}
