<?php

declare(strict_types=1);

if (! defined('ABSPATH')) {
    define('ABSPATH', sys_get_temp_dir() . '/enterprise-cpt-wp/');
}

if (! defined('ENTERPRISE_CPT_PATH')) {
    define('ENTERPRISE_CPT_PATH', dirname(__DIR__) . '/');
}

if (! function_exists('sanitize_key')) {
    function sanitize_key(string $key): string
    {
        $key = strtolower($key);
        $key = preg_replace('/[^a-z0-9_\-]/', '', $key);
        return $key === null ? '' : $key;
    }
}

if (! function_exists('get_stylesheet_directory')) {
    function get_stylesheet_directory(): string
    {
        return $GLOBALS['enterprise_cpt_theme_dir'];
    }
}

if (! function_exists('get_template_directory')) {
    function get_template_directory(): string
    {
        return $GLOBALS['enterprise_cpt_parent_theme_dir'];
    }
}

if (! function_exists('wp_upload_dir')) {
    function wp_upload_dir(mixed $time = null, bool $createDir = true): array
    {
        return ['basedir' => $GLOBALS['enterprise_cpt_uploads_dir']];
    }
}

if (! function_exists('trailingslashit')) {
    function trailingslashit(string $value): string
    {
        return rtrim($value, '/') . '/';
    }
}

if (! function_exists('esc_html')) {
    function esc_html(string $value): string
    {
        return htmlspecialchars($value, ENT_QUOTES, 'UTF-8');
    }
}

if (! function_exists('esc_attr')) {
    function esc_attr(string $value): string
    {
        return htmlspecialchars($value, ENT_QUOTES, 'UTF-8');
    }
}

if (! function_exists('esc_url')) {
    function esc_url(string $value): string
    {
        return filter_var($value, FILTER_SANITIZE_URL);
    }
}

if (! function_exists('wp_kses_post')) {
    function wp_kses_post(string $value): string
    {
        return $value;
    }
}

if (! function_exists('wpautop')) {
    function wpautop(string $value): string
    {
        return '<p>' . $value . '</p>';
    }
}

if (! function_exists('wp_json_encode')) {
    function wp_json_encode(mixed $value, int $flags = 0): string|false
    {
        return json_encode($value, $flags);
    }
}

if (! function_exists('wp_get_attachment_image')) {
    function wp_get_attachment_image(int $attachmentId, string $size = 'medium', bool $icon = false, array $attr = []): string
    {
        return $attachmentId > 0 ? '<img src="image-' . $attachmentId . '.jpg" alt="" />' : '';
    }
}

if (! function_exists('wp_get_attachment_url')) {
    function wp_get_attachment_url(int $attachmentId): string
    {
        return 'https://example.test/image-' . $attachmentId . '.jpg';
    }
}

if (! function_exists('get_attachment_link')) {
    function get_attachment_link(int $attachmentId): string
    {
        return 'https://example.test/attachment-' . $attachmentId;
    }
}

require __DIR__ . '/../vendor/autoload.php';

use EnterpriseCPT\Templates\Resolver;

function enterprise_cpt_template_remove_tree(string $path): void
{
    if (! is_dir($path)) {
        return;
    }

    foreach (scandir($path) ?: [] as $item) {
        if ($item === '.' || $item === '..') {
            continue;
        }

        $child = $path . DIRECTORY_SEPARATOR . $item;
        is_dir($child) ? enterprise_cpt_template_remove_tree($child) : unlink($child);
    }

    rmdir($path);
}

$tempRoot = sys_get_temp_dir() . '/enterprise-cpt-template-runtime-' . bin2hex(random_bytes(6));
$GLOBALS['enterprise_cpt_theme_dir'] = $tempRoot . '/theme';
$GLOBALS['enterprise_cpt_parent_theme_dir'] = $tempRoot . '/parent-theme';
$GLOBALS['enterprise_cpt_uploads_dir'] = $tempRoot . '/uploads';

mkdir($GLOBALS['enterprise_cpt_theme_dir'], 0777, true);
mkdir($GLOBALS['enterprise_cpt_parent_theme_dir'], 0777, true);
mkdir($GLOBALS['enterprise_cpt_uploads_dir'] . '/enterprise-cpt/templates', 0777, true);

$group = [
    'name' => 'product_details',
    'title' => 'Product Details',
    'fields' => [
        ['name' => 'headline', 'label' => 'Headline', 'type' => 'text'],
    ],
];

$fallbackTemplate = Resolver::get_block_template('product_details');

if ($fallbackTemplate !== ENTERPRISE_CPT_PATH . 'templates/generic-block.php') {
    echo "FAIL: missing theme/uploads template should resolve to the plugin fallback.\n";
    enterprise_cpt_template_remove_tree($tempRoot);
    exit(1);
}

$fallbackHtml = Resolver::render_block($group, ['headline' => 'Runtime Preview']);

if (! str_contains($fallbackHtml, 'Runtime Preview')) {
    echo "FAIL: plugin fallback template did not render field attributes.\n";
    enterprise_cpt_template_remove_tree($tempRoot);
    exit(1);
}

$uploadsTemplate = $GLOBALS['enterprise_cpt_uploads_dir'] . '/enterprise-cpt/templates/product_details.php';
file_put_contents($uploadsTemplate, "<?php\n// Auto-generated by Enterprise CPT.\n");

if (Resolver::get_block_template('product_details') !== $uploadsTemplate) {
    echo "FAIL: generated uploads template should be selected before plugin fallback.\n";
    enterprise_cpt_template_remove_tree($tempRoot);
    exit(1);
}

$generatedHtml = Resolver::render_block($group, ['headline' => 'Generated Preview']);

if (! str_contains($generatedHtml, 'Generated Preview')) {
    echo "FAIL: generated uploads template path should render schema-aware default markup.\n";
    enterprise_cpt_template_remove_tree($tempRoot);
    exit(1);
}

enterprise_cpt_template_remove_tree($tempRoot);

echo "PASS: SSR template resolver handles generated uploads and plugin fallback templates.\n";
exit(0);